INSERT INTO USER_SECURITY (username,password) VALUES ('javainuse','$2a$10$slYQmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6');
INSERT INTO GRANTED_AUTHORITY_CUSTOM (AUTHORITY) VALUES ('ROLE_USER');
INSERT INTO USER_SECURITY_AUTHORITIES (USER_SECURITY_ID,AUTHORITIES_ID) VALUES (1,1);

INSERT INTO USER_SECURITY (username,password) VALUES ('admin','$2a$10$g01pvrDXk1kMqsNSXD7nQe4d1OPlQk52D3JAQHyCARXR8IGiPGbVK');
INSERT INTO GRANTED_AUTHORITY_CUSTOM (AUTHORITY) VALUES ('ROLE_USER');
INSERT INTO USER_SECURITY_AUTHORITIES (USER_SECURITY_ID,AUTHORITIES_ID) VALUES (2,2);


